### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by baishengjun** [shang-qian/SCSit#1]
Hi, qian
I encounter the error `Segmentation fault (core dumped)` with test data, Does have any solution to solve this error?

Thanks in advance,
Bai

**Comment by baishengjun** [comment]
solved it.

**Comment by LuBeifang** [comment]
> Hi, qian I encounter the error `Segmentation fault (core dumped)` with test data, Does have any solution to solve this error?
> 
> Thanks in advance, Bai

Hi! How did you solve?
